language: scala
scala: 2.11.7
jdk:
    - oraclejdk8
install:
    - npm install
    - jspm config registries.github.auth $JSPM_GITHUB_AUTH_SECRET
    - jspm registry export github
    - jspm install
script:
    - grunt --stack validate test
    - sbt ++$TRAVIS_SCALA_VERSION compile test assets riffRaffUpload
env:
    global:
        # JSPM token
        - secure: B1MFxS39QdzsFyHFPIgbZp14bKEwnMkoXhUlzqxPGKgABhnD/khMGsJwkGolTLIXud/YXen2RYuphb1DpSYSoVHHQhZ1xuTjetGIajoMStNp+bkyTs5J5z1Lfbs6uYuES4cV9pcWi0TMam8ywkwijDZ7LSxcekEwG5//aIqug1UDYGDpzz1F4xDi5lPZSrW0P1u17t7BPvH6bCE/zUTbXnzFjnnloTG3LJYnDnmrAvFObF++hqCaDcg6iG3UGBUjSfgURv2fliX6/dLvm9dKMTQEI44MQaz92pIexLB8rVoPi+963a3clGnVx6gEePqsE+nV9VllhpSMcrj+VDXI26wEBopuXYtaxV4Cg34a/TNlAvPmv/cmBAucgUY0a1oHf1qXxgo21qA+nFUeu5TAEOEPJY+MvSA6oba3ODkzWMEQdtwd4BdEyaMf/2odxbZ4z3x7TfOOgK8ZY+8rY/92q8k+bq//IDOJdYDcF2NFY59d8W3swzMAQVT/dEjKuqUonQH+dbqCrLJLeE/+WD707bSEGnXufBp+/7HxgY7V0Z0Wtn7QFGil0TiYVJO6mPXNQHMIKh1dpqOYg+ZHTsC9BZDfuHeT6jfdmA0hGYRuIhWDvD+AqmHctGRPLNTiCkVBnmuZCn3GVcu0mUNsXHd9dZFbLx2KPXxNjZbeWbwYqqE=
        # RiffRaff upload keys and secret
        - secure: rqLMkxwFoViYYT+KulCa8vc7Q+8Od2hdD5L51/Cxre97Oe18Bx2+MtmvhpTNnjSDNjbvw6FXXeEWUg548+LvyIUwzTzWz7T+EnZVtXYWC45zr5966i7MC1vKRQO5VBvfoV62Y1EsbvFBHlFEVkyivo2vYZBW8EcInOvBH7mccAhXvsisVoV8jBjik2lA3rW1C3Hh5aVwvkgc/ajbzYvIBf36iexDZDPaRAibU+/d4WRUShYp+xCS/FhE7AW8GiWNcQF3VHRmY/1LXTSuaLa/zaIA+LT5u9K1q560krTEsWH8MMw8aflhCQCy0eYxazl+6/3d14Hwn1fh8ixUdEaWuitLMCQ43BFcaw688AVq6nKrQBNeZIo0jhhIPLJXiTM/OLHv6gJAHZVzB4g4QMt131JQgh6dPA5A7gT102csDQxsHFe6OoNRsyNY9UewAlkYR3jmmWENvl0A75jexAvHRzIZTqUSxnuZydMaZ+EhXDRCVGj8dUuxyk/A6CwFmgnxo+U4lN8ezjV0b4N0W6zOfwhLz2S5bMfXlrSn21mgwSgD5sjq03o76/OuLLW8mDagA4g2xzQCI/bZdeUGHirV90db/ZuM5yWwq6iflu41Fi+h6ejxg1s5MS62D4viQlKY6Vczz7eZ6Z26CywLrau5a4XbqRPo90s965ZrU4ZIEUE=
        - secure: GKLV4apiJXpovMqYq7cEGHRjYNsFtWBbca5UDy4n4S4Hlpbz14VtFG8iVmQEHAuQ8Wia7o8+WKfcdUKUoLFFMazk/yuA/NdKX6uyYSV9itBYEMPZBzR0Kta3bdSPOgeHDZixxvcbrj47a0XffPWbwEuQ7tNWlHTmaagvogBY6cXJ8J0CgS3FwAMpTfeakaoIMWGHNr0A5MgKlqxhfOxZIMxjwJToWxWk1E2fkJZTGSSzQdn2OdupAf98i8Y5cZ7hsZIRZ5N5dQzzDKrS+iNXHPM7ioXJLFgwf56QeReHyaWlk3Rg5ak911B6ssLSY+O1/AFJgG8B90VBmHsGxGPj9aDuhzBg00pRzVA9+lFi4qtA76vcKJQnZKQ44werZVfDsf8xjLiw3+MvunXi4zFhIiztBE+HnVgGrkjrra6wtW4GEl3wdFfbyQtsePuF1uxBduq43eue49YqcoIevAuEjeJVtBdAXL2eHFLZHTjqi9ZKDLVgrBU7CvsLR8JbtHp0BOm/f3N80lCo20kDDf7MVnlEJ2Up40wUM9UNtdGu57Ha3C5oh5/BJXg9SoTvXsr0BHh/V9da4khjxOfawQ/KedVkQoUF94fsQ00zyvOC+4ozfMY+JGa1c1gfGcX5kQTcyu0824Pn4h/bK0p4Vg7DuzxMbl6oOunXNudT1a4Ltno=
cache:
    directories:
        - node_modules
        - public/src/jspm_packages
        - ~/.ivy2/cache
        - ~/.sbt/boot/
        - ~/.nvm/
before_cache:
    - du -h -d 1 $HOME/.ivy2/
    - du -h -d 2 $HOME/.sbt/
    # Tricks to avoid unnecessary cache updates
    - find $HOME/.sbt -name "*.lock" -type f -delete
    - find $HOME/.ivy2 -name "ivydata-*.properties" -type f -delete
